### ISSUE TITLE
Two approaches, wee!

### ISSUE THREAD

**Issue by klocey** [klocey/AnthroMath#4]
@websterkgd  It seems like there's two approaches, Ken's approaches the actual square root from the right (higher values), and Kevin's approaches the square root from the left (lower than actual values). If so, this would be a good thing! Let's look into it. 

A common code base might be helpful. Python is my weapon of choice for computational tasks, e.g., loops. It has bullet proof mathematical capability and is many times faster than R, 'specially when compiled in Cython. But, I can use R for ease of collaboration. -KL

**Comment by websterkgd** [comment]
It sounds like I need to use Python. Maybe we can work on that a little tomorrow. Tomorrow should be epic.

**Comment by klocey** [comment]
And, it was!!!!!
